# **Merge two datasets to form large dataset**

The **concat()** function can be used to concatenate two Dataframes by adding the rows of one to the other. The **merge()** function is equivalent to the SQL JOIN clause. 'left', 'right' and 'inner' joins are all possible.

In [1]:
import pandas as pd
#View dataset 1
df1=pd.read_csv('dataset1.csv')
df1

   SL    Name University         Dept
0   1    Arif         DU          EEE
1   2    Ahad         DU         ILET
2   3   Sohel         DU          EEE
3   4    Gaus       NSTU     Pharmacy
4   5   Sovel       NSTU  Environment
5   6  Faisal         DU         Soil

In [2]:
#View dataset 2
df2=pd.read_csv('dataset2.csv')
df2

   SL        Job
0   1    Teacher
1   2     Banker
2   3    Teacher
3   4  Phamacist
4   5   Business
5   6     Banker

Method **pandas.merge()** and **DataFrame.merge()** are used to merge two or multiple DataFrames. Both these methods work exactly the same and they also take a similar number of params. Merging DataFrames is nothing but joining DataFrames similar to Database join.

In [3]:
#Merge these two datasets into one
df3=pd.merge(df1,df2)
df3

   SL    Name University         Dept        Job
0   1    Arif         DU          EEE    Teacher
1   2    Ahad         DU         ILET     Banker
2   3   Sohel         DU          EEE    Teacher
3   4    Gaus       NSTU     Pharmacy  Phamacist
4   5   Sovel       NSTU  Environment   Business
5   6  Faisal         DU         Soil     Banker

In [4]:
df3=pd.merge(df1,df2,on='SL') #same result will appear
df3

   SL    Name University         Dept        Job
0   1    Arif         DU          EEE    Teacher
1   2    Ahad         DU         ILET     Banker
2   3   Sohel         DU          EEE    Teacher
3   4    Gaus       NSTU     Pharmacy  Phamacist
4   5   Sovel       NSTU  Environment   Business
5   6  Faisal         DU         Soil     Banker

Similar to the Database join, merge() method also supports several join types like **left, right, inner, outer and cross.** Use how param to specify the join type.

By default merge() uses inner join on columns that are present on both DataFrames. You can also explicitly specify the columns you wanted to join on and join by row index.

Sometimes it is required to specify the column names you wanted to merge, to do so use on param. For example df3=pd.merge(df1,df2, on='Courses').

The “**outer**” merge combines all the rows for left and right dataframes with NaN when there are no matched values in the rows. Notice that the method indicator is set to True in order to indicate where each row originates from in the merge data — outer_merge.

In [8]:
#union operation (intersection if inner)
df3=pd.merge(df1,df2,on='SL',how='outer') 
df3

   SL    Name University         Dept        Job
0   1    Arif         DU          EEE    Teacher
1   2    Ahad         DU         ILET     Banker
2   3   Sohel         DU          EEE    Teacher
3   4    Gaus       NSTU     Pharmacy  Phamacist
4   5   Sovel       NSTU  Environment   Business
5   6  Faisal         DU         Soil     Banker

To merge Pandas DataFrame, use the merge() function. In that, you can set the parameter indicator to True or False. If you want to check which dataframe has a specific record, then use − **indicator= True**. As shown above, using above parameter as True, adds a column to the output DataFrame called “_merge”.

In [6]:
#check the avaiability of data in both datasets
df3=pd.merge(df1,df2,on='SL',how='outer',indicator= True) 
df3

   SL    Name University         Dept        Job _merge
0   1    Arif         DU          EEE    Teacher   both
1   2    Ahad         DU         ILET     Banker   both
2   3   Sohel         DU          EEE    Teacher   both
3   4    Gaus       NSTU     Pharmacy  Phamacist   both
4   5   Sovel       NSTU  Environment   Business   both
5   6  Faisal         DU         Soil     Banker   both

In [9]:
#check the avaiability of data in both datasets
df3=pd.merge(df1,df2,on='SL',how='right',indicator= True) 
df3

   SL    Name University         Dept        Job _merge
0   1    Arif         DU          EEE    Teacher   both
1   2    Ahad         DU         ILET     Banker   both
2   3   Sohel         DU          EEE    Teacher   both
3   4    Gaus       NSTU     Pharmacy  Phamacist   both
4   5   Sovel       NSTU  Environment   Business   both
5   6  Faisal         DU         Soil     Banker   both