# **Principle Component Analysis (PCA)**

In [2]:
#Importing libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas import read_csv
%matplotlib inline

In [4]:
#Load the data
df=pd.read_csv('heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [20]:
#separate input and output
x=df.drop('target',axis=True)
Y=df['target']

In [21]:
#Standardize the data 
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x)

StandardScaler()

The 'fit' method trains the algorithm on the training data, after the model is initialized. That's really all it does. So the sklearn fit method uses the training data as an input to train the machine learning model.

In [22]:
X=scaler.transform(x)
X

array([[-0.26843658,  0.66150409, -0.91575542, ...,  0.99543334,
         1.20922066,  1.08985168],
       [-0.15815703,  0.66150409, -0.91575542, ..., -2.24367514,
        -0.73197147,  1.08985168],
       [ 1.71659547,  0.66150409, -0.91575542, ..., -2.24367514,
        -0.73197147,  1.08985168],
       ...,
       [-0.81983438,  0.66150409, -0.91575542, ..., -0.6241209 ,
         0.23862459, -0.52212231],
       [-0.4889957 , -1.51170646, -0.91575542, ...,  0.99543334,
        -0.73197147, -0.52212231],
       [-0.04787747,  0.66150409, -0.91575542, ..., -0.6241209 ,
         0.23862459,  1.08985168]])

The transform() function is used to call function on self producing a Series with transformed values and that has the same axis length as self.

In [25]:
#PCA implementation
from sklearn.decomposition import PCA
pca=PCA(n_components=5)
pca.fit(x)
X=pca.transform(x)

In [26]:
#shape of input features before PCA
x.shape

(1025, 13)

In [27]:
#shape of input features after PCA
X.shape

(1025, 5)

In [28]:
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3

In [29]:
X

array([[-3.46150835e+01, -1.86266035e+01, -2.96171344e+00,
         2.70879333e+00,  1.31405353e+00],
       [-4.26252744e+01, -4.15863028e+00,  1.10033267e+01,
        -3.82499209e-01,  2.28026779e+00],
       [-7.02018426e+01,  2.93674774e+01,  1.63068595e+01,
         1.14768294e+01,  9.66273513e-01],
       ...,
       [ 2.79970293e+01,  2.66501996e+01, -2.71524130e+01,
        -1.00565036e+01, -2.09564820e-02],
       [ 6.59023617e+00, -1.25290520e+01, -2.11928402e+01,
         1.59831161e-01, -6.14921314e-01],
       [-5.79613421e+01,  3.58205878e+01, -1.23879913e+01,
        -2.83716091e+00,  1.58873100e-01]])

In [30]:
#Split into Train and Test Sets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
test_size = 0.33
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=test_size,
random_state=seed)
#Fit the model
model = LogisticRegression()
model.fit(X_train, Y_train)
#Accuracy finding
result = model.score(X_test, Y_test)
result

0.8053097345132744