**Feature Selection for Machine Learning**

What are the advantages of feature selection process? Why is Feature Selection important?

In the machine learning process, feature selection is used to make the process more accurate. It also increases the prediction power of the algorithms by selecting the most critical variables and eliminating the redundant and irrelevant ones.

Which feature selection method is best in machine learning?

Exhaustive feature selection is one of the best feature selection methods, which evaluates each feature set as brute-force. It means this method tries & make each possible combination of features and return the best performing feature set.

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("diabetes.csv")
#view first 5 rows
df.head()

   6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [2]:
#Add labels
filename='diabetes.csv'
names=['preg','glu','bp','skin','insulin','bmi','pedi','age','class']
df=pd.read_csv(filename,names=names)
#view first 20 rows
df.head(20)

    preg  glu  bp  skin  insulin   bmi   pedi  age  class
0      6  148  72    35        0  33.6  0.627   50      1
1      1   85  66    29        0  26.6  0.351   31      0
2      8  183  64     0        0  23.3  0.672   32      1
3      1   89  66    23       94  28.1  0.167   21      0
4      0  137  40    35      168  43.1  2.288   33      1
5      5  116  74     0        0  25.6  0.201   30      0
6      3   78  50    32       88  31.0  0.248   26      1
7     10  115   0     0        0  35.3  0.134   29      0
8      2  197  70    45      543  30.5  0.158   53      1
9      8  125  96     0        0   0.0  0.232   54      1
10     4  110  92     0        0  37.6  0.191   30      0
11    10  168  74     0        0  38.0  0.537   34      1
12    10  139  80     0        0  27.1  1.441   57      0
13     1  189  60    23      846  30.1  0.398   59      1
14     5  166  72    19      175  25.8  0.587   51      1
15     7  100   0     0        0  30.0  0.484   32      1
16     0  118  84    47      230  45.8  0.551   31      1
17     7  107  74     0        0  29.6  0.254   31      1
18     1  103  30    38       83  43.3  0.183   33      0
19     1  115  70    30       96  34.6  0.529   32      1

In [3]:
#separate input and output
X=df.drop('class',axis=True)
Y=df['class']

**Univariate Selection**

**Univariate Selection:** Statistical tests can be used to select those features that have the strongest relationship with the output variable. The scikit-learn library provides the SelectKBest class that can be used with a suite of different statistical tests to select a specific number of features.

Univariate analysis refers to the quantitative data exploration we do at the beginning of any analysis. These analyses provide us with descriptions of single variables we are interested in using in more advanced tests and help us narrow down exactly what types of bivariate and multivariate analyses we should carry out.

The **SelectKBest** method selects the features according to the k highest score. By changing the 'score_func' parameter we can apply the method for both classification and regression data. Selecting best features is important process when we prepare a large dataset for training.

A **chi-square test** is used in statistics to test the independence of two events. A significance level of 0.05 indicates a 5% risk of concluding that an association between the variables exists when there is no actual association.

SelectKBest will select the K most explicative features out of the original set, so **K should be a value greater than 0 and lower or equal than the total number of features**.

The larger the Chi-square value, the greater the probability that there really is a significant difference. There is a significant difference between the groups we are studying. **A very small chi square test statistic means means there is a high correlation between the observed and expected values. Therefore, the sample data is a good fit for what would be expected in the general population.**

In [4]:
# feature extraction
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]
[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]]

**Recursive Feature Elimination**

**Recursive feature elimination (RFE)** is a feature selection method that fits a model and removes the weakest feature (or features) until the specified number of features is reached. 
RFE is popular because it is easy to configure and use and because it is effective at selecting those features (columns) in a training dataset that are more or most relevant in predicting the target variable.

In [ ]:
from sklearn.datasets import make_friedman1
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
X, Y = make_friedman1(n_samples=50, n_features=10, random_state=0)
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=5, step=1)
selector = selector.fit(X, Y)
selector.support_
selector.ranking_

array([1, 1, 1, 1, 1, 6, 4, 3, 2, 5])

**Principle Component Analysis**

**Principal component analysis (PCA)** is a technique for reducing the dimensionality of such datasets, increasing interpretability but at the same time minimizing information loss. It does so by creating new uncorrelated variables that successively maximize variance.

PCA technique is particularly useful in processing data where multi-colinearity exists between the features/variables. PCA can be used when the dimensions of the input features are high (e.g. a lot of variables). PCA can be also used for denoising and data compression. PCA helps in overcoming the overfitting issue by reducing the number of features. It is very hard to visualize and understand the data in high dimensions. PCA transforms a high dimensional data to low dimensional data (2 or 3 dimension) so that it can be visualized easily. PCA won't be effective with categorical variables since they lack a variance structure (they are not numerical).

**pca = PCA(n_components=?)**

In other words, when we apply PCA to the original dataset with p number of variables to get a transformed dataset with k number of variables (principal components), n_components is equal to k, where the value of k is much less than the value of p.

In [5]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
fit=pca.fit(X)
# summarize components
print(fit.components_)

[[-2.022e-03  9.781e-02  1.609e-02  6.076e-02  9.931e-01  1.401e-02
   5.372e-04 -3.565e-03]
 [-2.265e-02 -9.722e-01 -1.419e-01  5.786e-02  9.463e-02 -4.697e-02
  -8.168e-04 -1.402e-01]
 [-2.246e-02  1.434e-01 -9.225e-01 -3.070e-01  2.098e-02 -1.324e-01
  -6.400e-04 -1.255e-01]]

**Feature Importance**

**Feature (variable) importance** indicates how much each feature contributes to the model prediction. Basically, it determines the degree of usefulness of a specific variable for a current model and prediction. Feature Importance refers to techniques that calculate a score for all the input features for a given model — the scores simply represent the “importance” of each feature. A higher score means that the specific feature will have a larger effect on the model that is being used to predict a certain variable.

**ExtraTrees Classifier** can be used for classification or regression, in scenarios where computational cost is a concern and features have been carefully selected and analyzed. Extra Trees can be implemented from Scikit-learn.

In [6]:
from sklearn.ensemble import ExtraTreesClassifier
model=ExtraTreesClassifier()
model.fit(X,Y)
print(model.feature_importances_)

[0.112 0.23  0.101 0.078 0.078 0.143 0.119 0.139]